### ISSUE TITLE
Support for bowerJavascripts and bowerStylesheets

### ISSUE THREAD

**Issue by sheerun** [ck86/gulp-bower-files#19]
Your plugin tries to compile main css to my javascript ;)

**Comment by ck86** [comment]
My plugin does nothing with your files, it just selects them. What you do with them is up to you. ;-)

You have two options if you want to compile the javascript files:  
1.  You can override the main property for the bower components, so that there are no css files included.
2.  You can use [gulp-filter](https://github.com/sindresorhus/gulp-filter)
