### ISSUE TITLE
Generate string rather than gulp.src()

### ISSUE THREAD

**Issue by silvenon** [ck86/gulp-bower-files#31]
That way we could do this:

``` js
gulp.src([bowerFiles(), 'another/path'])
```

Maybe there's another way to join `gulp.src()`s that I'm not aware of.

**Comment by ck86** [comment]
`bowerFiles()` can return a stream with more than one file, so it should return an array. Another option is to use [streamqueue](https://npmjs.org/package/streamqueue), see [here](https://github.com/gulpjs/gulp/issues/255).

**Comment by silvenon** [comment]
I tried it now and it works. Thanks! :smiley:

**Comment by darbychang** [comment]
I've tried streamqueue and it works fine. But I still would like to see that gulp-bower-files() can return an array (maybe an option to control this feature). It's because that a path array can be easily converted to a streamqueue with gulp.src(). But the inverse from stream to path array is not.

BTW, my suggestion is because LiveScript provides an extremely easy way for array concatenation. It looks like

```
gulp.src( gulp.bower-files() ++ ['another/path'] );
```
